version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - revive
    - staticcheck
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      ignore-comments: true
    gocognit:
      min-complexity: 10
    gocritic:
      enabled-checks:
        - commentedOutCode
        - nilValReturn
        - sloppyReassign
        - weakCond
        - octalLiteral
        - appendCombine
        - equalFold
        - hugeParam
        - indexAlloc
        - rangeExprCopy
        - rangeValCopy
        - boolExprSimplify
        - commentedOutImport
        - docStub
        - emptyFallthrough
        - emptyStringTest
        - hexLiteral
        - methodExprCall
        - stringXbytes
        - typeAssertChain
        - unlabelStmt
        - yodaStyleExpr
        - builtinShadow
        - importShadow
        - initClause
        - nestingReduce
        - paramTypeCombine
        - ptrToRefParam
        - typeUnparen
        - unnamedResult
        - unnecessaryBlock
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    govet:
      enable:
        - fieldalignment
    nolintlint:
      require-specific: true
      allow-unused: false
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              ignoreFuncs: os\.*,fmt\.*,make,viper\.*
              maxLitCount: "5"
          exclude:
            - TEST
        - name: cognitive-complexity
          disabled: true
        - name: confusing-naming
          exclude:
            - TEST
        - name: cyclomatic
          disabled: true
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          exclude:
            - TEST
        - name: unhandled-error
          arguments:
            - fmt\..*
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
    testifylint:
      enable-all: true
    varnamelen:
      ignore-names:
        - fn
        - id
        - tx
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - goconst
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: ""
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/protobom/storage)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
