// Code generated by ent, DO NOT EDIT.
// --------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2024 The Protobom Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// --------------------------------------------------------------

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/protobom/storage/internal/backends/ent/node"
	"github.com/protobom/storage/internal/backends/ent/predicate"
	"github.com/protobom/storage/internal/backends/ent/purpose"
)

// PurposeUpdate is the builder for updating Purpose entities.
type PurposeUpdate struct {
	config
	hooks    []Hook
	mutation *PurposeMutation
}

// Where appends a list predicates to the PurposeUpdate builder.
func (pu *PurposeUpdate) Where(ps ...predicate.Purpose) *PurposeUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetNodeID sets the "node_id" field.
func (pu *PurposeUpdate) SetNodeID(u uuid.UUID) *PurposeUpdate {
	pu.mutation.SetNodeID(u)
	return pu
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (pu *PurposeUpdate) SetNillableNodeID(u *uuid.UUID) *PurposeUpdate {
	if u != nil {
		pu.SetNodeID(*u)
	}
	return pu
}

// ClearNodeID clears the value of the "node_id" field.
func (pu *PurposeUpdate) ClearNodeID() *PurposeUpdate {
	pu.mutation.ClearNodeID()
	return pu
}

// SetPrimaryPurpose sets the "primary_purpose" field.
func (pu *PurposeUpdate) SetPrimaryPurpose(pp purpose.PrimaryPurpose) *PurposeUpdate {
	pu.mutation.SetPrimaryPurpose(pp)
	return pu
}

// SetNillablePrimaryPurpose sets the "primary_purpose" field if the given value is not nil.
func (pu *PurposeUpdate) SetNillablePrimaryPurpose(pp *purpose.PrimaryPurpose) *PurposeUpdate {
	if pp != nil {
		pu.SetPrimaryPurpose(*pp)
	}
	return pu
}

// SetNode sets the "node" edge to the Node entity.
func (pu *PurposeUpdate) SetNode(n *Node) *PurposeUpdate {
	return pu.SetNodeID(n.ID)
}

// Mutation returns the PurposeMutation object of the builder.
func (pu *PurposeUpdate) Mutation() *PurposeMutation {
	return pu.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (pu *PurposeUpdate) ClearNode() *PurposeUpdate {
	pu.mutation.ClearNode()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PurposeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PurposeUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PurposeUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PurposeUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PurposeUpdate) check() error {
	if v, ok := pu.mutation.PrimaryPurpose(); ok {
		if err := purpose.PrimaryPurposeValidator(v); err != nil {
			return &ValidationError{Name: "primary_purpose", err: fmt.Errorf(`ent: validator failed for field "Purpose.primary_purpose": %w`, err)}
		}
	}
	return nil
}

func (pu *PurposeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(purpose.Table, purpose.Columns, sqlgraph.NewFieldSpec(purpose.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.PrimaryPurpose(); ok {
		_spec.SetField(purpose.FieldPrimaryPurpose, field.TypeEnum, value)
	}
	if pu.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   purpose.NodeTable,
			Columns: []string{purpose.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   purpose.NodeTable,
			Columns: []string{purpose.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{purpose.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PurposeUpdateOne is the builder for updating a single Purpose entity.
type PurposeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PurposeMutation
}

// SetNodeID sets the "node_id" field.
func (puo *PurposeUpdateOne) SetNodeID(u uuid.UUID) *PurposeUpdateOne {
	puo.mutation.SetNodeID(u)
	return puo
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (puo *PurposeUpdateOne) SetNillableNodeID(u *uuid.UUID) *PurposeUpdateOne {
	if u != nil {
		puo.SetNodeID(*u)
	}
	return puo
}

// ClearNodeID clears the value of the "node_id" field.
func (puo *PurposeUpdateOne) ClearNodeID() *PurposeUpdateOne {
	puo.mutation.ClearNodeID()
	return puo
}

// SetPrimaryPurpose sets the "primary_purpose" field.
func (puo *PurposeUpdateOne) SetPrimaryPurpose(pp purpose.PrimaryPurpose) *PurposeUpdateOne {
	puo.mutation.SetPrimaryPurpose(pp)
	return puo
}

// SetNillablePrimaryPurpose sets the "primary_purpose" field if the given value is not nil.
func (puo *PurposeUpdateOne) SetNillablePrimaryPurpose(pp *purpose.PrimaryPurpose) *PurposeUpdateOne {
	if pp != nil {
		puo.SetPrimaryPurpose(*pp)
	}
	return puo
}

// SetNode sets the "node" edge to the Node entity.
func (puo *PurposeUpdateOne) SetNode(n *Node) *PurposeUpdateOne {
	return puo.SetNodeID(n.ID)
}

// Mutation returns the PurposeMutation object of the builder.
func (puo *PurposeUpdateOne) Mutation() *PurposeMutation {
	return puo.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (puo *PurposeUpdateOne) ClearNode() *PurposeUpdateOne {
	puo.mutation.ClearNode()
	return puo
}

// Where appends a list predicates to the PurposeUpdate builder.
func (puo *PurposeUpdateOne) Where(ps ...predicate.Purpose) *PurposeUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PurposeUpdateOne) Select(field string, fields ...string) *PurposeUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Purpose entity.
func (puo *PurposeUpdateOne) Save(ctx context.Context) (*Purpose, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PurposeUpdateOne) SaveX(ctx context.Context) *Purpose {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PurposeUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PurposeUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PurposeUpdateOne) check() error {
	if v, ok := puo.mutation.PrimaryPurpose(); ok {
		if err := purpose.PrimaryPurposeValidator(v); err != nil {
			return &ValidationError{Name: "primary_purpose", err: fmt.Errorf(`ent: validator failed for field "Purpose.primary_purpose": %w`, err)}
		}
	}
	return nil
}

func (puo *PurposeUpdateOne) sqlSave(ctx context.Context) (_node *Purpose, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(purpose.Table, purpose.Columns, sqlgraph.NewFieldSpec(purpose.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Purpose.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, purpose.FieldID)
		for _, f := range fields {
			if !purpose.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != purpose.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.PrimaryPurpose(); ok {
		_spec.SetField(purpose.FieldPrimaryPurpose, field.TypeEnum, value)
	}
	if puo.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   purpose.NodeTable,
			Columns: []string{purpose.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   purpose.NodeTable,
			Columns: []string{purpose.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Purpose{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{purpose.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
