// Code generated by ent, DO NOT EDIT.
// --------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2024 The Protobom Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// --------------------------------------------------------------
package ent

import (
	"github.com/protobom/storage/internal/backends/ent/document"
	"github.com/protobom/storage/internal/backends/ent/metadata"
	"github.com/protobom/storage/internal/backends/ent/node"
	"github.com/protobom/storage/internal/backends/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescTags is the schema descriptor for tags field.
	documentDescTags := documentFields[1].Descriptor()
	// document.DefaultTags holds the default value on creation for the tags field.
	document.DefaultTags = documentDescTags.Default.([]string)
	metadataFields := schema.Metadata{}.Fields()
	_ = metadataFields
	// metadataDescID is the schema descriptor for id field.
	metadataDescID := metadataFields[0].Descriptor()
	// metadata.IDValidator is a validator for the "id" field. It is called by the builders before save.
	metadata.IDValidator = metadataDescID.Validators[0].(func(string) error)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescID is the schema descriptor for id field.
	nodeDescID := nodeFields[0].Descriptor()
	// node.IDValidator is a validator for the "id" field. It is called by the builders before save.
	node.IDValidator = nodeDescID.Validators[0].(func(string) error)
}
