-- --------------------------------------------------------------
-- SPDX-FileCopyrightText: Copyright © 2026 The Protobom Authors
-- SPDX-FileType: SOURCE
-- SPDX-License-Identifier: Apache-2.0
-- --------------------------------------------------------------
--
-- Generic (portable) SQL schema for storing protobom SBOM data, fully
-- normalized with NO JSON columns.
--
-- This is the same logical model as schema.ansi.sql, but the four inline JSON
-- array columns are replaced by ordered child tables so the schema works on
-- engines without a JSON type and keeps every value individually queryable:
--   nodes.licenses      -> node_licenses
--   nodes.attribution   -> node_attributions
--   nodes.file_types    -> node_file_types
--   node_lists.root_elements -> node_list_roots
-- Each of these tables carries an `ordinal` column that preserves the original
-- order of the protobuf repeated field.
--
-- TYPE MAPPING
--   The DDL below uses a small set of generic type names. Map them to the
--   nearest equivalent for your engine if it does not accept them verbatim:
--     TEXT      -> VARCHAR(n) / CLOB / NVARCHAR(max)        (variable length text)
--     BOOLEAN   -> BOOLEAN / TINYINT(1) / INTEGER 0|1
--     TIMESTAMP -> TIMESTAMP / TIMESTAMPTZ / DATETIME       (UTC instants)
--     SMALLINT  -> SMALLINT / INTEGER                       (protobuf enum codes)
--     INTEGER   -> INTEGER                                  (ordinals)
--     BIGINT    -> BIGINT / INTEGER                         (surrogate keys, sizes)
--
--   Surrogate primary keys use the SQL-standard
--     GENERATED BY DEFAULT AS IDENTITY
--   form. Engines that do not support it need the local equivalent
--   (PostgreSQL: BIGSERIAL/IDENTITY, MySQL: AUTO_INCREMENT,
--    SQLite: INTEGER PRIMARY KEY AUTOINCREMENT).
--
-- ENUM CODES
--   All enum-typed columns store the raw protobuf enum NUMBER (not the label).
--   The integer for each value is the one declared in sbom.proto. A short legend
--   is given inline; the complete mapping is in README.md.
--
-- Tables are declared in dependency order so the file can be applied top to
-- bottom in a single transaction.

-- ====================================================================
-- Document graph roots
-- ====================================================================

-- A single SBOM document. The id is the document identifier (CycloneDX serial
-- number or SPDX document SPDXID), mirroring Metadata.id in the proto.
CREATE TABLE documents (
    id   TEXT NOT NULL,
    PRIMARY KEY (id)
);

-- Document-level metadata. One row per document (1:1).
CREATE TABLE metadata (
    document_id TEXT      NOT NULL,
    version     TEXT      NOT NULL DEFAULT '',
    name        TEXT      NOT NULL DEFAULT '',
    date        TIMESTAMP NULL,            -- Metadata.date (creation time, UTC)
    comment     TEXT      NOT NULL DEFAULT '',
    PRIMARY KEY (document_id),
    CONSTRAINT fk_metadata_document
        FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE
);

-- Metadata.documentTypes: classification of the document (repeated DocumentType).
-- type stores DocumentType.SBOMType: 0 OTHER, 1 DESIGN, 2 SOURCE, 3 BUILD,
-- 4 ANALYZED, 5 DEPLOYED, 6 RUNTIME, 7 DISCOVERY, 8 DECOMISSION (NULL = unset).
CREATE TABLE document_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id TEXT     NOT NULL,
    type        SMALLINT NULL,
    name        TEXT     NULL,
    description TEXT     NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_document_types_metadata
        FOREIGN KEY (document_id) REFERENCES metadata (document_id) ON DELETE CASCADE
);
CREATE INDEX idx_document_types_document ON document_types (document_id);

-- Metadata.tools: tools used to produce the document (repeated Tool).
CREATE TABLE tools (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id TEXT NOT NULL,
    name        TEXT NOT NULL DEFAULT '',
    version     TEXT NOT NULL DEFAULT '',
    vendor      TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (id),
    CONSTRAINT fk_tools_metadata
        FOREIGN KEY (document_id) REFERENCES metadata (document_id) ON DELETE CASCADE
);
CREATE INDEX idx_tools_document ON tools (document_id);

-- Metadata.source_data: provenance of the original SBOM document (1:1 metadata).
CREATE TABLE source_data (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id TEXT   NOT NULL,
    format      TEXT   NOT NULL DEFAULT '',  -- e.g. text/spdx+json;version=2.3
    size        BIGINT NULL,                 -- original size in bytes
    uri         TEXT   NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_source_data_document UNIQUE (document_id),
    CONSTRAINT fk_source_data_metadata
        FOREIGN KEY (document_id) REFERENCES metadata (document_id) ON DELETE CASCADE
);

-- SourceData.hashes: map<HashAlgorithm, value> of the original document.
-- algorithm stores HashAlgorithm (0 UNKNOWN, 1 MD5, 2 SHA1, 3 SHA256, ...).
CREATE TABLE source_data_hashes (
    source_data_id BIGINT   NOT NULL,
    algorithm      SMALLINT NOT NULL,
    hash_value     TEXT     NOT NULL,
    PRIMARY KEY (source_data_id, algorithm),
    CONSTRAINT fk_source_data_hashes_source_data
        FOREIGN KEY (source_data_id) REFERENCES source_data (id) ON DELETE CASCADE
);

-- ====================================================================
-- Nodes
-- ====================================================================

-- NodeList: the graph container holding the document's nodes and edges (1:1
-- document). Its root element ids live in node_list_roots.
CREATE TABLE node_lists (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id TEXT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_node_lists_document UNIQUE (document_id),
    CONSTRAINT fk_node_lists_document
        FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE
);

-- Node: a software component (the central vertex of the SBOM graph).
-- Nodes are keyed by their protobom id and linked to node lists through
-- node_list_nodes, which allows the same node to be shared across documents.
-- type stores Node.NodeType: 0 PACKAGE, 1 FILE.
CREATE TABLE nodes (
    id                TEXT      NOT NULL,
    type              SMALLINT  NOT NULL DEFAULT 0,
    name              TEXT      NOT NULL DEFAULT '',
    version           TEXT      NOT NULL DEFAULT '',
    file_name         TEXT      NOT NULL DEFAULT '',
    url_home          TEXT      NOT NULL DEFAULT '',
    url_download      TEXT      NOT NULL DEFAULT '',
    license_concluded TEXT      NOT NULL DEFAULT '',
    license_comments  TEXT      NOT NULL DEFAULT '',
    copyright         TEXT      NOT NULL DEFAULT '',
    source_info       TEXT      NOT NULL DEFAULT '',
    comment           TEXT      NOT NULL DEFAULT '',
    summary           TEXT      NOT NULL DEFAULT '',
    description       TEXT      NOT NULL DEFAULT '',
    release_date      TIMESTAMP NULL,
    build_date        TIMESTAMP NULL,
    valid_until_date  TIMESTAMP NULL,
    PRIMARY KEY (id)
);
CREATE INDEX idx_nodes_name ON nodes (name);
CREATE INDEX idx_nodes_type ON nodes (type);

-- Membership of nodes in node lists (NodeList.nodes), many-to-many.
CREATE TABLE node_list_nodes (
    node_list_id BIGINT NOT NULL,
    node_id      TEXT   NOT NULL,
    PRIMARY KEY (node_list_id, node_id),
    CONSTRAINT fk_node_list_nodes_list
        FOREIGN KEY (node_list_id) REFERENCES node_lists (id) ON DELETE CASCADE,
    CONSTRAINT fk_node_list_nodes_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);
CREATE INDEX idx_node_list_nodes_node ON node_list_nodes (node_id);

-- NodeList.root_elements: ordered list of root node ids.
CREATE TABLE node_list_roots (
    node_list_id BIGINT  NOT NULL,
    ordinal      INTEGER NOT NULL,   -- position in the repeated field (0-based)
    node_id      TEXT    NOT NULL,
    PRIMARY KEY (node_list_id, ordinal),
    CONSTRAINT fk_node_list_roots_list
        FOREIGN KEY (node_list_id) REFERENCES node_lists (id) ON DELETE CASCADE,
    CONSTRAINT fk_node_list_roots_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);
CREATE INDEX idx_node_list_roots_node ON node_list_roots (node_id);

-- ====================================================================
-- Node scalar string arrays (normalized, order-preserving)
-- ====================================================================

-- Node.licenses: repeated string.
CREATE TABLE node_licenses (
    node_id TEXT    NOT NULL,
    ordinal INTEGER NOT NULL,        -- position in the repeated field (0-based)
    license TEXT    NOT NULL,
    PRIMARY KEY (node_id, ordinal),
    CONSTRAINT fk_node_licenses_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);

-- Node.attribution: repeated string.
CREATE TABLE node_attributions (
    node_id     TEXT    NOT NULL,
    ordinal     INTEGER NOT NULL,    -- position in the repeated field (0-based)
    attribution TEXT    NOT NULL,
    PRIMARY KEY (node_id, ordinal),
    CONSTRAINT fk_node_attributions_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);

-- Node.file_types: repeated string.
CREATE TABLE node_file_types (
    node_id   TEXT    NOT NULL,
    ordinal   INTEGER NOT NULL,      -- position in the repeated field (0-based)
    file_type TEXT    NOT NULL,
    PRIMARY KEY (node_id, ordinal),
    CONSTRAINT fk_node_file_types_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);

-- ====================================================================
-- Node sub-collections
-- ====================================================================

-- Node.identifiers: map<SoftwareIdentifierType, value>.
-- type stores SoftwareIdentifierType: 0 UNKNOWN, 1 PURL, 2 CPE22, 3 CPE23, 4 GITOID.
CREATE TABLE node_identifiers (
    node_id TEXT     NOT NULL,
    type    SMALLINT NOT NULL,
    value   TEXT     NOT NULL,
    PRIMARY KEY (node_id, type),
    CONSTRAINT fk_node_identifiers_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);
CREATE INDEX idx_node_identifiers_value ON node_identifiers (value);

-- Node.hashes: map<HashAlgorithm, value>.
CREATE TABLE node_hashes (
    node_id    TEXT     NOT NULL,
    algorithm  SMALLINT NOT NULL,
    hash_value TEXT     NOT NULL,
    PRIMARY KEY (node_id, algorithm),
    CONSTRAINT fk_node_hashes_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);
CREATE INDEX idx_node_hashes_value ON node_hashes (hash_value);

-- Node.primary_purpose: repeated Purpose.
-- purpose stores Purpose (0 UNKNOWN_PURPOSE, 1 APPLICATION, 2 ARCHIVE, ...).
CREATE TABLE node_purposes (
    node_id TEXT     NOT NULL,
    purpose SMALLINT NOT NULL,
    PRIMARY KEY (node_id, purpose),
    CONSTRAINT fk_node_purposes_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);

-- Node.properties: repeated Property (key/value pairs).
CREATE TABLE node_properties (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    node_id TEXT NOT NULL,
    name    TEXT NOT NULL DEFAULT '',
    data    TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (id),
    CONSTRAINT fk_node_properties_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);
CREATE INDEX idx_node_properties_node ON node_properties (node_id);

-- Node.external_references: repeated ExternalReference.
-- type stores ExternalReference.ExternalReferenceType (0 UNKNOWN .. 60 WEBSITE).
CREATE TABLE external_references (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    node_id   TEXT     NOT NULL,
    url       TEXT     NOT NULL DEFAULT '',
    comment   TEXT     NOT NULL DEFAULT '',
    authority TEXT     NULL,
    type      SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_external_references_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);
CREATE INDEX idx_external_references_node ON external_references (node_id);

-- ExternalReference.hashes: map<HashAlgorithm, value>.
CREATE TABLE external_reference_hashes (
    external_reference_id BIGINT   NOT NULL,
    algorithm             SMALLINT NOT NULL,
    hash_value            TEXT     NOT NULL,
    PRIMARY KEY (external_reference_id, algorithm),
    CONSTRAINT fk_external_reference_hashes_ref
        FOREIGN KEY (external_reference_id) REFERENCES external_references (id) ON DELETE CASCADE
);

-- ====================================================================
-- Edges (relationships between nodes)
-- ====================================================================

-- Edge: a typed relationship rooted at one node (Edge.from). The target nodes
-- (Edge.to, repeated) are stored in edge_targets.
-- type stores Edge.Type (0 UNKNOWN, 1 amends, 2 ancestor, ... 44 variant).
CREATE TABLE edges (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    node_list_id BIGINT   NOT NULL,
    type         SMALLINT NOT NULL DEFAULT 0,
    from_node_id TEXT     NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_edges_node_list
        FOREIGN KEY (node_list_id) REFERENCES node_lists (id) ON DELETE CASCADE,
    CONSTRAINT fk_edges_from_node
        FOREIGN KEY (from_node_id) REFERENCES nodes (id) ON DELETE CASCADE
);
CREATE INDEX idx_edges_node_list ON edges (node_list_id);
CREATE INDEX idx_edges_from_node ON edges (from_node_id);

-- Edge.to: the target nodes of an edge.
CREATE TABLE edge_targets (
    edge_id    BIGINT NOT NULL,
    to_node_id TEXT   NOT NULL,
    PRIMARY KEY (edge_id, to_node_id),
    CONSTRAINT fk_edge_targets_edge
        FOREIGN KEY (edge_id) REFERENCES edges (id) ON DELETE CASCADE,
    CONSTRAINT fk_edge_targets_node
        FOREIGN KEY (to_node_id) REFERENCES nodes (id) ON DELETE CASCADE
);
CREATE INDEX idx_edge_targets_node ON edge_targets (to_node_id);

-- ====================================================================
-- Persons (authors, suppliers, originators, contacts)
-- ====================================================================

-- Person represents an individual or organization. A person is attached to
-- exactly one owner via one of the nullable foreign keys below, matching the
-- four places Person is referenced in the proto:
--   metadata_id            -> Metadata.authors
--   supplier_of_node_id    -> Node.suppliers
--   originator_of_node_id  -> Node.originators
--   contact_of_person_id   -> Person.contacts (self reference, recursive)
CREATE TABLE persons (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name                  TEXT    NOT NULL DEFAULT '',
    is_org                BOOLEAN NOT NULL DEFAULT FALSE,
    email                 TEXT    NOT NULL DEFAULT '',
    url                   TEXT    NOT NULL DEFAULT '',
    phone                 TEXT    NOT NULL DEFAULT '',
    metadata_id           TEXT    NULL,
    supplier_of_node_id   TEXT    NULL,
    originator_of_node_id TEXT    NULL,
    contact_of_person_id  BIGINT  NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_persons_metadata
        FOREIGN KEY (metadata_id) REFERENCES metadata (document_id) ON DELETE CASCADE,
    CONSTRAINT fk_persons_supplier_node
        FOREIGN KEY (supplier_of_node_id) REFERENCES nodes (id) ON DELETE CASCADE,
    CONSTRAINT fk_persons_originator_node
        FOREIGN KEY (originator_of_node_id) REFERENCES nodes (id) ON DELETE CASCADE,
    CONSTRAINT fk_persons_contact_of
        FOREIGN KEY (contact_of_person_id) REFERENCES persons (id) ON DELETE CASCADE
);
CREATE INDEX idx_persons_metadata ON persons (metadata_id);
CREATE INDEX idx_persons_supplier_node ON persons (supplier_of_node_id);
CREATE INDEX idx_persons_originator_node ON persons (originator_of_node_id);
CREATE INDEX idx_persons_contact_of ON persons (contact_of_person_id);
