// Code generated by ent, DO NOT EDIT.
// --------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2024 The Protobom Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// --------------------------------------------------------------

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// DocumentType is the predicate function for documenttype builders.
type DocumentType func(*sql.Selector)

// EdgeType is the predicate function for edgetype builders.
type EdgeType func(*sql.Selector)

// ExternalReference is the predicate function for externalreference builders.
type ExternalReference func(*sql.Selector)

// HashesEntry is the predicate function for hashesentry builders.
type HashesEntry func(*sql.Selector)

// IdentifiersEntry is the predicate function for identifiersentry builders.
type IdentifiersEntry func(*sql.Selector)

// Metadata is the predicate function for metadata builders.
type Metadata func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// NodeList is the predicate function for nodelist builders.
type NodeList func(*sql.Selector)

// Person is the predicate function for person builders.
type Person func(*sql.Selector)

// Purpose is the predicate function for purpose builders.
type Purpose func(*sql.Selector)

// Tool is the predicate function for tool builders.
type Tool func(*sql.Selector)
